# Development Dockerfile
FROM node:20-alpine AS development

# Set working directory
WORKDIR /app

# Copy package.json and yarn.lock to install dependencies
COPY package.json yarn.lock Makefile ./

# Install dependencies
RUN make install

# Copy the rest of the app's source code
COPY . .

# Expose port 8080 for development server
EXPOSE 8080

# Start the development server
CMD ["make", "run"]
