name: CI
run-name: ${{ github.actor }} is running CI

on:
  push:
    branches: ['*']
    paths-ignore:
      - 'README.md'
      - '.docs/**'
  pull_request:
    branches: [main, master, develop]
    paths-ignore:
      - 'README.md'
      - '.docs/**'

jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set environment variables
        run: |
          echo "VITE_APP_API_URL=${{ secrets.VITE_APP_API_URL }}" > .env
          echo "VITE_APP_ENABLE_API_MOCKING=${{ secrets.VITE_APP_ENABLE_API_MOCKING }}" > .env

      - name: Install all related dependencies
        run: make install

      - name: Run lint
        run: make run-lint

      - name: Run prettier
        run: make format

      - name: Check types
        run: make check-types

      - name: Run unit test
        run: make test

      - name: Run build application
        run: make build

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set environment variables
        run: |
          echo "VITE_APP_API_URL=${{ secrets.VITE_APP_API_URL }}" > .env
          echo "VITE_APP_ENABLE_API_MOCKING=${{ secrets.VITE_APP_ENABLE_API_MOCKING }}" > .env

      - name: Install all related dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: make test-e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
